# Use postgres/example user/password credentials
version: '3.3'

services:

  lendingclubapp:
    image: lendingclub
    environment:
      - ACTIVE_PROFILE=docker
    ports:
      - "8888:8888"
    depends_on:
      - "db"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
#      start_period: 30s

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - "8181:8080"
