server.port: 8888

spring.datasource.url: "jdbc:postgresql://db:5432/postgres"
spring.datasource.driverClassName: org.postgresql.Driver
spring.datasource.username: postgres
spring.datasource.password: example
spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql: true
spring.jpa.hibernate.ddl-auto: create-only
spring.datasource.hikari.connection-timeout: 2000
